// import './main.html';
import '../imports/client/ui/components/login.js';
import '../imports/client/ui/components/nav.js';
import '../imports/client/ui/components/sidenav.js';
import '../imports/client/startup/accounts-config.js';
import '../imports/client/routing/routes.js';
import '../imports/client/ui/pages/index.js';
import '../imports/client/ui/pages/admin.js';
// import '../imports/client/ui/pages/bread.js';
// import '../imports/client/ui/pages/veggies.js';
// import '../imports/client/ui/pages/grains.js';
// import '../imports/client/ui/pages/milk.js';